// create/templates/react/pages/form.jsx
import React from 'react';
import {
  Page,
  Navbar,
  List,
  ListInput,
  ListItem,
  Toggle,
  BlockTitle,
  Row,
  Button,
  Range,
  Block
} from 'techno4-react';

const FormPage = () => (
  <Page name="form">
    <Navbar title="Form" backLink="Back"></Navbar>

    <BlockTitle>Form Example</BlockTitle>
    <List noHairlinesMd>
      <ListInput
        label="Name"
        type="text"
        placeholder="Your name"
      ></ListInput>

      <ListInput
        label="E-mail"
        type="email"
        placeholder="E-mail"
      ></ListInput>

      <ListInput
        label="URL"
        type="url"
        placeholder="URL"
      ></ListInput>

      <ListInput
        label="Password"
        type="password"
        placeholder="Password"
      ></ListInput>

      <ListInput
        label="Phone"
        type="tel"
        placeholder="Phone"
      ></ListInput>

      <ListInput
        label="Gender"
        type="select"
        >
        <option>Male</option>
        <option>Female</option>
      </ListInput>

      <ListInput
        label="Birth date"
        type="date"
        placeholder="Birth day"
        defaultValue="2014-04-30"
      ></ListInput>

      <ListItem
        title="Toggle"
      >
        <Toggle slot="after" />
      </ListItem>

      <ListInput
        label="Range"
        input={false}
      >
        <Range slot="input" value={50} min={0} max={100} step={1} />
      </ListInput>

      <ListInput
        type="textarea"
        label="Textarea"
        placeholder="Bio"
      ></ListInput>
      <ListInput
        type="textarea"
        label="Resizable"
        placeholder="Bio"
        resizable
      ></ListInput>
    </List>

    <BlockTitle>Buttons</BlockTitle>
    <Block strong>
      <Row tag="p">
        <Button className="col">Button</Button>
        <Button className="col" fill>Fill</Button>
      </Row>
      <Row tag="p">
        <Button className="col" raised>Raised</Button>
        <Button className="col" raised fill>Raised Fill</Button>
      </Row>
      <Row tag="p">
        <Button className="col" round>Round</Button>
        <Button className="col" round fill>Round Fill</Button>
      </Row>
      <Row tag="p">
        <Button className="col" outline>Outline</Button>
        <Button className="col" round outline>Outline Round</Button>
      </Row>
      <Row tag="p">
        <Button className="col" small outline>Small</Button>
        <Button className="col" small round outline>Small Round</Button>
      </Row>
      <Row tag="p">
        <Button className="col" small fill>Small</Button>
        <Button className="col" small round fill>Small Round</Button>
      </Row>
      <Row tag="p">
        <Button className="col" large raised>Large</Button>
        <Button className="col" large fill raised>Large Fill</Button>
      </Row>
      <Row tag="p">
        <Button className="col" large fill raised color="red">Large Red</Button>
        <Button className="col" large fill raised color="green">Large Green</Button>
      </Row>
    </Block>

    <BlockTitle>Checkbox group</BlockTitle>
    <List>
      <ListItem
        checkbox
        name="my-checkbox"
        value="Books"
        title="Books"
      ></ListItem>
      <ListItem
        checkbox
        name="my-checkbox"
        value="Movies"
        title="Movies"
      ></ListItem>
      <ListItem
        checkbox
        name="my-checkbox"
        value="Food"
        title="Food"
      ></ListItem>
    </List>

    <BlockTitle>Radio buttons group</BlockTitle>
    <List>
      <ListItem
        radio
        name="radio"
        value="Books"
        title="Books"
      ></ListItem>
      <ListItem
        radio
        name="radio"
        value="Movies"
        title="Movies"
      ></ListItem>
      <ListItem
        radio
        name="radio"
        value="Food"
        title="Food"
      ></ListItem>
    </List>
  </Page>
);

export default FormPage;

// create/templates/vue/pages/form.vue
<template>
  <t4-page name="form">
    <t4-navbar title="Form" back-link="Back"></t4-navbar>

    <t4-block-title>Form Example</t4-block-title>
    <t4-list no-hairlines-md>
      <t4-list-input
        label="Name"
        type="text"
        placeholder="Your name"
      ></t4-list-input>

      <t4-list-input
        label="E-mail"
        type="email"
        placeholder="E-mail"
      ></t4-list-input>

      <t4-list-input
        label="URL"
        type="url"
        placeholder="URL"
      ></t4-list-input>

      <t4-list-input
        label="Password"
        type="password"
        placeholder="Password"
      ></t4-list-input>

      <t4-list-input
        label="Phone"
        type="tel"
        placeholder="Phone"
      ></t4-list-input>

      <t4-list-input
        label="Gender"
        type="select"
        >
        <option>Male</option>
        <option>Female</option>
      </t4-list-input>

      <t4-list-input
        label="Birth date"
        type="date"
        placeholder="Birth day"
        defaultValue="2014-04-30"
      ></t4-list-input>

      <t4-list-item
        title="Toggle"
      >
        <template #after>
          <t4-toggle />
        </template>
      </t4-list-item>

      <t4-list-input
        label="Range"
        :input="false"
      >
        <template #input>
          <t4-range :value="50" :min="0" :max="100" :step="1" />
        </template>
      </t4-list-input>

      <t4-list-input
        type="textarea"
        label="Textarea"
        placeholder="Bio"
      ></t4-list-input>
      <t4-list-input
        type="textarea"
        label="Resizable"
        placeholder="Bio"
        resizable
      ></t4-list-input>
    </t4-list>

    <t4-block-title>Buttons</t4-block-title>
    <t4-block strong>
      <t4-row tag="p">
        <t4-button class="col">Button</t4-button>
        <t4-button class="col" fill>Fill</t4-button>
      </t4-row>
      <t4-row tag="p">
        <t4-button class="col" raised>Raised</t4-button>
        <t4-button class="col" raised fill>Raised Fill</t4-button>
      </t4-row>
      <t4-row tag="p">
        <t4-button class="col" round>Round</t4-button>
        <t4-button class="col" round fill>Round Fill</t4-button>
      </t4-row>
      <t4-row tag="p">
        <t4-button class="col" outline>Outline</t4-button>
        <t4-button class="col" round outline>Outline Round</t4-button>
      </t4-row>
      <t4-row tag="p">
        <t4-button class="col" small outline>Small</t4-button>
        <t4-button class="col" small round outline>Small Round</t4-button>
      </t4-row>
      <t4-row tag="p">
        <t4-button class="col" small fill>Small</t4-button>
        <t4-button class="col" small round fill>Small Round</t4-button>
      </t4-row>
      <t4-row tag="p">
        <t4-button class="col" large raised>Large</t4-button>
        <t4-button class="col" large fill raised>Large Fill</t4-button>
      </t4-row>
      <t4-row tag="p">
        <t4-button class="col" large fill raised color="red">Large Red</t4-button>
        <t4-button class="col" large fill raised color="green">Large Green</t4-button>
      </t4-row>
    </t4-block>

    <t4-block-title>Checkbox group</t4-block-title>
    <t4-list>
      <t4-list-item
        checkbox
        name="my-checkbox"
        value="Books"
        title="Books"
      ></t4-list-item>
      <t4-list-item
        checkbox
        name="my-checkbox"
        value="Movies"
        title="Movies"
      ></t4-list-item>
      <t4-list-item
        checkbox
        name="my-checkbox"
        value="Food"
        title="Food"
      ></t4-list-item>
    </t4-list>

    <t4-block-title>Radio buttons group</t4-block-title>
    <t4-list>
      <t4-list-item
        radio
        name="radio"
        value="Books"
        title="Books"
      ></t4-list-item>
      <t4-list-item
        radio
        name="radio"
        value="Movies"
        title="Movies"
      ></t4-list-item>
      <t4-list-item
        radio
        name="radio"
        value="Food"
        title="Food"
      ></t4-list-item>
    </t4-list>
  </t4-page>
</template>
