// create/templates/vue/pages/product.vue
<template>
  <t4-page name="product">
    <t4-navbar :title="product.title" back-link="Back"></t4-navbar>
    <t4-block-title>About {{product.title}}</t4-block-title>
    <t4-block strong>
      {{product.description}}
    </t4-block>
  </t4-page>
</template>
<script>
  import { useStore } from 'techno4-vue';

  export default {
    props: {
      t4route: Object,
    },
    setup(props) {
      const products = useStore('products');
      const productId = props.t4route.params.id;
      let currentProduct;
      products.value.forEach(function (product) {
        if (product.id === productId) {
          currentProduct = product;
        }
      });
      return {
        product: currentProduct,
      };
    },
  };
</script>

// create/templates/svelte/pages/product.svelte
<Page name="product">
  <Navbar title={currentProduct.title} backLink="Back" />
  <BlockTitle>About {currentProduct.title}</BlockTitle>
  <Block strong>
    {currentProduct.description}
  </Block>
</Page>
<script>
  import { Page, Navbar, BlockTitle, Block, useStore } from 'techno4-svelte';

  export let t4route;

  const products = useStore('products');
  const productId = t4route.params.id;
  let currentProduct;
  products.forEach(function (product) {
    if (product.id === productId) {
      currentProduct = product;
    }
  });
</script>
